[package]
name = "data8-lib"
version = "0.1.0"
entrypoint = "src/lib.typ"
repository = ""
authors = ["Tim Xie <xie@berkeley.edu>"]
license = "MIT"
description = "Worksheet and exam template for Data 8 at UC Berkeley."
keywords = ["exam", "worksheet", "assignment", "quiz"]
categories = ["layout", "model", "utility"]
exclude = ["**/*.pdf"]
